Chen:
	/usr/bin/env g++ -Wall -fPIC -I "/usr/include/python3.9" -I "/usr/include/python3.9/cpython" -I "/usr/lib/python3.9/site-packages/numpy/core/include" -lpython3.9 -I . -I ../headers -o "Chen.o" "Chen.cpp"
	chmod +x Chen.o
	./Chen.o

doublePendulum:
	/usr/bin/env g++ -Wall -fPIC -I "/usr/include/python3.9" -I "/usr/include/python3.9/cpython" -I "/usr/lib/python3.9/site-packages/numpy/core/include" -lpython3.9 -I . -I ../headers -o "doublePendulum.o" "doublePendulum.cpp"
	chmod +x doublePendulum.o
	./doublePendulum.o

elasticPendulum:
	/usr/bin/env g++ -Wall -fPIC -I "/usr/include/python3.9" -I "/usr/include/python3.9/cpython" -I "/usr/lib/python3.9/site-packages/numpy/core/include" -lpython3.9 -I . -I ../headers -o "elasticPendulum.o" "elasticPendulum.cpp"
	chmod +x elasticPendulum.o
	./elasticPendulum.o

Lorenz:
	/usr/bin/env g++ -Wall -fPIC -I "/usr/include/python3.9" -I "/usr/include/python3.9/cpython" -I "/usr/lib/python3.9/site-packages/numpy/core/include" -lpython3.9 -I . -I ../headers -o "Lorenz.o" "Lorenz.cpp"
	chmod +x Lorenz.o
	./Lorenz.o

Rossler:
	/usr/bin/env g++ -Wall -fPIC -I "/usr/include/python3.9" -I "/usr/include/python3.9/cpython" -I "/usr/lib/python3.9/site-packages/numpy/core/include" -lpython3.9 -I . -I ../headers -o "Rossler.o" "Rossler.cpp"
	chmod +x Rossler.o
	./Rossler.o

simplePendulum:
	/usr/bin/env g++ -Wall -fPIC -I "/usr/include/python3.9" -I "/usr/include/python3.9/cpython" -I "/usr/lib/python3.9/site-packages/numpy/core/include" -lpython3.9 -I . -I ../headers -o "simplePendulum.o" "simplePendulum.cpp"
	chmod +x simplePendulum.o
	./simplePendulum.o

SEIR:
	/usr/bin/env g++ -Wall -fPIC -I "/usr/include/python3.9" -I "/usr/include/python3.9/cpython" -I "/usr/lib/python3.9/site-packages/numpy/core/include" -lpython3.9 -I . -I ../headers -o "SEIR.o" "SEIR.cpp"
	chmod +x SEIR.o
	./SEIR.o

SIR:
	/usr/bin/env g++ -Wall -fPIC -I "/usr/include/python3.9" -I "/usr/include/python3.9/cpython" -I "/usr/lib/python3.9/site-packages/numpy/core/include" -lpython3.9 -I . -I ../headers -o "SIR.o" "SIR.cpp"
	chmod +x SIR.o
	./SIR.o

debug-Chen:
	/usr/bin/env g++ -g -Wall -fPIC -I "/usr/include/python3.9" -I "/usr/include/python3.9/cpython" -I "/usr/lib/python3.9/site-packages/numpy/core/include" -lpython3.9 -I . -I ../headers -o "Chen.o" "Chen.cpp"
	chmod +x Chen.o
	gdb Chen.o

debug-doublePendulum:
	/usr/bin/env g++ -g -Wall -fPIC -I "/usr/include/python3.9" -I "/usr/include/python3.9/cpython" -I "/usr/lib/python3.9/site-packages/numpy/core/include" -lpython3.9 -I . -I ../headers -o "doublePendulum.o" "doublePendulum.cpp"
	chmod +x doublePendulum.o
	gdb doublePendulum.o

debug-elasticPendulum:
	/usr/bin/env g++ -g -Wall -fPIC -I "/usr/include/python3.9" -I "/usr/include/python3.9/cpython" -I "/usr/lib/python3.9/site-packages/numpy/core/include" -lpython3.9 -I . -I ../headers -o "elasticPendulum.o" "elasticPendulum.cpp"
	chmod +x elasticPendulum.o
	gdb elasticPendulum.o

debug-Lorenz:
	/usr/bin/env g++ -g -Wall -fPIC -I "/usr/include/python3.9" -I "/usr/include/python3.9/cpython" -I "/usr/lib/python3.9/site-packages/numpy/core/include" -lpython3.9 -I . -I ../headers -o "Lorenz.o" "Lorenz.cpp"
	chmod +x Lorenz.o
	gdb Lorenz.o

debug-Rossler:
	/usr/bin/env g++ -g -Wall -fPIC -I "/usr/include/python3.9" -I "/usr/include/python3.9/cpython" -I "/usr/lib/python3.9/site-packages/numpy/core/include" -lpython3.9 -I . -I ../headers -o "Rossler.o" "Rossler.cpp"
	chmod +x Rossler.o
	gdb Rossler.o

debug-simplePendulum:
	/usr/bin/env g++ -g -Wall -fPIC -I "/usr/include/python3.9" -I "/usr/include/python3.9/cpython" -I "/usr/lib/python3.9/site-packages/numpy/core/include" -lpython3.9 -I . -I ../headers -o "simplePendulum.o" "simplePendulum.cpp"
	chmod +x simplePendulum.o
	gdb simplePendulum.o

debug-SEIR:
	/usr/bin/env g++ -g -Wall -fPIC -I "/usr/include/python3.9" -I "/usr/include/python3.9/cpython" -I "/usr/lib/python3.9/site-packages/numpy/core/include" -lpython3.9 -I . -I ../headers -o "SEIR.o" "SEIR.cpp"
	chmod +x SEIR.o
	gdb SEIR.o

debug-SIR:
	/usr/bin/env g++ -g -Wall -fPIC -I "/usr/include/python3.9" -I "/usr/include/python3.9/cpython" -I "/usr/lib/python3.9/site-packages/numpy/core/include" -lpython3.9 -I . -I ../headers -o "SIR.o" "SIR.cpp"
	chmod +x SIR.o
	gdb SIR.o
